version: '3'

services:
  nuxt:
    build: .
    tty: true
    command: npm run dev
    volumes:
      - .:/app
    ports:
      - "8080:3000"
  proxy:
    image: psimonov/cors-anywhere
    ports:
      - "8081:3000"
