version: 2.1
orbs:
  node: circleci/node@1.1
workflows:
  node:
    jobs:
      build:
        executor:
          name: node/default
          tag: '12.13'
        steps:
          - checkout
          - node/with-cache:
              steps:
                - run: npm install
          - run: npm run test
